import Layout from "../components/Layout";
import Head from "next/head";
import { GlobalStyle } from "../components/GlobalStyle";
// import "@/styles/globals.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Dominic Freytag</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/DF3.png" />
        <link
          rel="apple-touch-icon"
          type="image/png"
          href="/Img/DF2.png"
          sizes="180x180"
        />
      </Head>
      <GlobalStyle />
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}
